# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'thesisregistry-sc'
  azureSubscription: 'thesis-azure-sc'
  imageRepository: 'thesisfront'
  containerRegistry: 'thesisregistry-a2anexeebgawbdha.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  webAppName: 'thesis-frontend-dev'
  VITE_API_URL: 'https://thesis-backend-dev-d3b5h4cncmcsh2hb.polandcentral-01.azurewebsites.net'
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: BuildDeploy
  displayName: Build push and deploy stage
  jobs:
  - job: BuildPushDeploy
    displayName: Build push deploy
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build image
      inputs:
        command: build
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest
        arguments: '--build-arg VITE_API_URL=$(VITE_API_URL)'

    - task: Docker@2
      displayName: Push image
      inputs:
        command: push
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest

    - task: AzureWebAppContainer@1
      displayName: Deploy to frontend web app
      inputs:
        azureSubscription: $(azureSubscription)
        appName: $(webAppName)
        imageName: $(containerRegistry)/$(imageRepository):$(tag)